import BeforeNav from "@/components/BeforeNav";
import "./globals.css";
import { DM_Serif_Display } from "next/font/google";
import Navbar from "@/components/Navbar";

const dmSerif = DM_Serif_Display({
  subsets: ["latin"],
  weight: "400",
  style: "normal",
  variable: "--font-dm-serif",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSerif.variable} bg-bg min-h-screen text-zinc-100`}>
        <div className="relative overflow-hidden">
          <BeforeNav />
          <div className="relative mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
